version=0.1
[default.build.parameters]
beta_features = true

[default.sync.parameters]
beta_features = true

[default.deploy.parameters]
stack_name = "event-processing"
region = "eu-west-2"
tags = "project=\"di-txma-event_processor\" stage=\"develop\""
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides=[
    "Environment=dev",
    "CodeSigningConfigArn=none",
    "PermissionsBoundary=none"
]

[dev.deploy.parameters]
stack_name = "event-processing"
region = "eu-west-2"
tags = "project=\"di-txma-event_processor\" stage=\"develop\""
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides=[
    "Environment=dev",
    "CodeSigningConfigArn=none",
    "PermissionsBoundary=none"
]

[build.deploy.parameters]
stack_name = "event-processing"
region = "eu-west-2"
tags = "project=\"di-txma-event_processor\" stage=\"build\""
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides=[
    "Environment=build"
]

[staging.deploy.parameters]
stack_name = "event-processing"
region = "eu-west-2"
tags = "project=\"di-txma-event_processor\" stage=\"staging\""
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides=[
    "Environment=staging"
]

[production.deploy.parameters]
stack_name = "event-processing"
region = "eu-west-2"
tags = "project=\"di-txma-event_processor\" stage=\"production\""
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides=[
    "Environment=production"
]

[integration.deploy.parameters]
stack_name = "event-processing"
region = "eu-west-2"
tags = "project=\"di-txma-event_processor\" stage=\"integration\""
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides=[
    "Environment=integration"
]
